### ISSUE TITLE
Introduce pre-commit hooks

### ISSUE THREAD

**Issue by alefnula** [arXiv/arxiv-search#262]
I would like to introduce some pre-commit hooks to check and format the code before it can be committed to the repository. I would use [pre-commit](https://pre-commit.com/) to do this and the configuration for it would look like this:

```yaml
- repo: https://github.com/ambv/black
  rev: stable
  hooks:
    - id: black
      name: Format Python Code
      language: python
      entry: black
      args:
        - --safe
        - --line-length=79
        - --target-version=py36
        - search

- repo: https://gitlab.com/pycqa/flake8
  rev: 3.7.9
  hooks:
    - id: flake8
      name: Flake8 Check
      language: python
      entry: flake8
      args:
        - search

- repo: https://github.com/pycqa/pydocstyle
  rev: master
  hooks:
    - id: pydocstyle
      name: Python Documentation Style Check
      language: python
      entry: pydocstyle
      args:
        - search
```

I could add some other checkers like:

- [mypy](https://mypy-lang.org/)
- [pytype - 🦆✔ \| pytype](https://google.github.io/pytype/)
- [GitHub - microsoft/pyright: Static type checker for Python](https://github.com/Microsoft/pyright)
- [Pyre · A performant type-checker for Python 3](https://pyre-check.org)
- [CrossHair](https://github.com/pschanely/CrossHair)

Tests won't be included in the pre-commit hooks since they take a substantial amount of time (and will probably take even more as the project progresses so I'd leave them to the CI system.

Also question is there a reason you are still using python 3.6?
